### ISSUE TITLE
[low] publish changelog & confirm links to it

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-accessibility-principles#28]
Hi @yatil, Let me know if there's anything for me to do to get this published and linked:

https://github.com/w3c/wai-accessibility-principles/blob/master/changelog.md

**Comment by yatil** [comment]
This is uploading now. (Noticed that I content is now in a content folder for new repositories, for example the file you linked above is now at https://github.com/w3c/wai-accessibility-principles/blob/master/content/changelog.md? That is because I learned from the errors and made it much more fool [=me] proof. Previously I had to specify each individual file for inclusion in the rendering of the site and I forgot the changelog. Now I just say “everything in the content folder” and I cannot forget any pages, including translations. Much better.)
